language: node_js
node_js:
- 8.11.4
services:
- postgresql
cache:
  directories:
  - node_modules\
before_install:
  - npm install -g nyc
  -
env:
  global:
  - NODE_ENV=development
  - ENABLE_SSL=false

script:
- npm test
- npm run coverage

after_success:
- npm run coverage
