language: node_js
node_js:
- 8.11.4
services:
- postgresql
cache:
  directories:
  - node_modules\
before_install:
  - npm install -g nyc
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
env:
  global:
  - NODE_ENV=development
  - ENABLE_SSL=false

script:
- npm test

after_success:
- npm run coverage
