import cloudinary from 'cloudinary';
import dotenv from 'dotenv';

dotenv.config();


cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const uploads = {};

console.log('** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **');
function performTransformations() {
  console.log();
  console.log();
  console.log();
  console.log('>> >> >> >> >> >> >> >> >> >>  Transformations << << << << << << << << << <<');
  console.log();
  console.log('> Fit into 200x150');
  console.log(`> ${cloudinary.url(uploads.pizza2.public_id, {
    width: 200, height: 150, crop: 'fit', format: 'jpg',
  })}`);

  console.log();
  console.log('> Eager transformation of scaling to 200x150');
  console.log(`> ${cloudinary.url(uploads.lake.public_id, eager_options)}`);

  console.log();
  console.log('> Face detection based 200x150 thumbnail');
  console.log(`> ${cloudinary.url(uploads.couple.public_id, {
    width: 200, height: 150, crop: 'thumb', gravity: 'faces', format: 'jpg',
  })}`);

  console.log();
  console.log('> Fill 200x150, round corners, apply the sepia effect');
  console.log(`> ${cloudinary.url(uploads.couple2.public_id, {
    width: 200, height: 150, crop: 'fill', gravity: 'face', radius: 10, effect: 'sepia', format: 'jpg',
  })}`);

  console.log();
  console.log("> That's it. You can now open the URLs above in a browser");
  console.log('> and check out the generated images.');
}

// Here, the transformation is applied to the uploaded image BEFORE storing it on the cloud.
// The original uploaded image is discarded.

function waitForAllUploads(id, err, image) {
  uploads[id] = image;
  const ids = Object.keys(uploads);
  if (ids.length == 6) {
    console.log();
    console.log(`**  uploaded all files (${ids.join(',')}) to cloudinary`);
    performTransformations();
  }
  cloudinary.uploader.upload('http://res.cloudinary.com/demo/image/upload/couple.jpg',
    {
      tags: 'basic_sample', width: 500, height: 500, crop: 'fit', effect: 'saturation:-70',
    },
    (err, image) => {
      console.log();
      console.log('** Remote Url');
      if (err) { console.warn(err); }
      console.log(`* ${image.public_id}`);
      console.log(`* ${image.url}`);
      waitForAllUploads('couple2', err, image);
    });
  // File upload
  cloudinary.uploader.upload('pizza.jpg', { tags: 'basic_sample' }, (err, image) => {
    console.log();
    console.log('** File Upload');
    if (err) { console.warn(err); }
    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
    console.log(`* ${image.public_id}`);
    console.log(`* ${image.url}`);
    waitForAllUploads('pizza', err, image);
  });
}
